### PR TITLE
Completed Issue #18 of Task #66

### LINKED ISSUE #18: Test & Implement 	get(int i, int j)
```
public double get(int i,
                  int j)
Get a single element.
Parameters:
i - Row index.
j - Column index.
Returns:
A(i,j)
Throws:
java.lang.ArrayIndexOutOfBoundsException
```

### PR DESCRIPTION
**Pull request by campellcl**
This closes #18  of task #66.

### CODE REVIEW

File: javatrix/Matrix.java [hunk 1]
```diff
@@ -182,14 +182,22 @@ public Matrix copy()
...
      * @return     [description]
      */
-    public double get(int i, int j)
+    public double get(int i, int j) throws IndexOutOfBoundsException
     {
-        return 0;
+        if (i < 0 || i >= a.length) {
+            throw new IndexOutOfBoundsException();
+        }
+        else if (j < 0 || j > a[i].length) {
```
Comment (whereswaldon) [inline javatrix/Matrix.java]: Shouldn't the second part of this be `j >= a[i].length`

File: junit/MatrixTest.java [hunk 2]
```diff
@@ -260,7 +261,38 @@ public void testCtorFillWithConstb()
...
+     *  in retrieving the element at the specified index.
+     */
+    @Test
+    public void testGet(){
+        double[][] testMatrix = {{1,2,3,4},{5,6,7,8},{9,10,11,12}};
+        Matrix matrix = new Matrix(testMatrix);
+        int[] testIndex = new int[2];
+        Random rand = new Random();
+        //create the index 'i' for which to test equivalency
+        testIndex[0] = rand.nextInt(2) + 0;
```
Comment (whereswaldon) [inline junit/MatrixTest.java]: Why ` + 0`?

**Review by whereswaldon — CHANGES_REQUESTED** [review]
Got a couple questions before we merge this one.

File: junit/MatrixTest.java (hunk 2 above)
Comment (campellcl) [reply junit/MatrixTest.java]: I thought that the '+ x' sets the minimum value so that: `rand.nextInt(20) + 5` produces integers of range 5 - 20 inclusive. This may be incorrect, i'll look it up early tomorrow morning.
EDIT: This is [not the case](https://docs.oracle.com/javase/7/docs/api/java/util/Random.html#nextInt(int)), removing the zeros.

File: javatrix/Matrix.java (hunk 1 above)
Comment (campellcl) [reply javatrix/Matrix.java]: It should, good catch.

**Review by whereswaldon — APPROVED** [review]
Okay, looks good now.
